- name: Print a message
  hosts: localhost
  vars:
    URL: play.google.com
  tasks:
    - name: Print a message using variable
      ansible.builtin.debug:
        msg: URL = {{URL}}
    - name: Print variable declared in tasks
      vars:
        URL: task.google.com
        ansible.builtin.debug:
          msg: URL = {{URL}}
  roles:
    - demo