- name: conditions in ansible
  hosts: localhost
  tasks:
    - name: Print a Hello, John
      ansible.builtin.debug:
        msg: Hello, John
      when: {{ item }} == John

    - name: Print a Hello, Ram
      ansible.builtin.debug:
        msg: Hello, Ram
      when: {{ item }} == Ram