- name: conditions in ansible
  hosts: localhost
  vars:
    epic: false
    monumental: "true"
  tasks:
#    - name: Print a Hello, John
#      ansible.builtin.debug:
#        msg: Hello, John
#      when: user == John
#
#    - name: Print a Hello, Ram
#      ansible.builtin.debug:
#        msg: Hello, Ram
#      when: user == "Ram"

    - name: Run the command if "epic" or "monumental" is true
      ansible.builtin.debug:
        msg: This certainly is epic!
      when: epic and monumental | bool

#    - name: Run the command if "epic" is false
#      ansible.builtin.shell: echo "This certainly isn't epic!"
#      when: not epic