- name: Loops
  hosts: localhost
  tasks:
    - name: Loop demo
      ansible.builtin.debug:
        msg: Hello, {{ item }} #calling a particular variable using item (default)
      loop:
        - Ram
        - John
        - Steve
#maps input in loops

    - name: Loop demo on maps
      ansible.builtin.debug:
        msg: Hello, {{ item.name }}, Age of yours is {{ item.age }} years.
      loop:
        - { name: "Ram", age: 20, run: true } #JSON input
        - { name: "John", age: 30, run: false }
        - { name: "Steve", age: 40, run: true }
      when: item.run # boolean when true it will run