- name: Print names
  hosts: localhost
  tasks:
    - name: Loop demo
      ansible.builtin.debug:
        msg: Hello, {{ item }}
      loop:
        - Ram
        - John
        - Seen
#Maps in loop
    - name: Maps in loop
      ansible.builtin.debug:
        msg: Hello, {{ item.name }}, Age {{ item.age }} years.
      loop:
        - { name: 'Ram', age: 30, run: true }
        - { name: 'John', age: 31, run: false }
        - { name: 'Seen', age: 32, run: true }
      when: item.run