- name: Register
  hosts: localhost
  tasks:
    - name: Shell
      ansible.builtin.shell:
        cmd: uptime
      register: out

    - name: Print output
      ansible.builtin.debug:
        msg:
          - system time - {{out}}
