- name: Register
  hosts: localhost
  tasks:
    - name: Shell
      ansible.builtin.shell: uptime #the task command will register into a variable (out) will be used in later task
      register: out # out is variable and will store the output into a variable.

    - name: Print Shell output
      ansible.builtin.debug:
        msg: "{{ out }}"