- name: Filters
  hosts: localhost
  vars:
    URL: https://nginx.org/download/nginx-1.25.3.zip
  tasks:
    - name: Filters
      ansible.builtin.unarchive:
        src: "{{ URL }}"
        dest: /tmp
        remote_src: yes

    - name: URL split
      ansible.builtin.debug:
        msg: "{{ URL | split ('/') | last | regex_replace ('.zip') }}" # double quotes inside a double quote is a problem use single quote.